### ISSUE TITLE
J - Crear la documentacion para las refactorizaciones del antes y el despues

### ISSUE THREAD

**Issue by juanF18** [anything-devs/actualizArte-Mantenimieto#11]

**Comment by cristianHenao00** [comment]
Se agregaron las tres refactorizaciones solicitadas para el proyecto se crea documento con los pantallazos antes y después de cada una. [Enlace](https://docs.google.com/document/d/1IzjxO-RVOxYniN265d7mOpARqInBuc0RHqTzqRh3yc4/edit)
