### ISSUE TITLE
K - Mejorar comentarios de 2 metodos

### ISSUE THREAD

**Issue by juanF18** [anything-devs/actualizArte-Mantenimieto#12]

**Comment by juanF18** [comment]
@Manuela-Rendon Revisar la estructura de como se están creando los comentarios
Se estan haciendo:

> // Aca va el comentario

Se deverian hacer

> /** 
>     Aca va el comentario
> */

**Comment by Manuela-Rendon** [comment]
Se realizan los cambios en los comentarios
