### ISSUE TITLE
F - Crear documento con los resultados del analisis estatico

### ISSUE THREAD

**Issue by juanF18** [anything-devs/actualizArte-Mantenimieto#7]
- [ ] Mostrar cantidad de advertencias

- [ ] Cantidad de violaciones de cada tipo 

- [ ] Breve explicación de los principales hallazgos

**Comment by Manuela-Rendon** [comment]
Se realizó el análisis estático de código con SonarLint y se documentó en el siguiente documento.
[Análisis estático](https://docs.google.com/document/d/1Bzu-pkd6O3NtxappEbm5F-XCi1URalja2qnhIjRpxCQ/edit?usp=drive_link)
